version: '3.8'
services:
  web:
    build: .
    restart: always
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
