version: '3.8'
services:
  web:
    build: .
    restart: always
    environment:
      RAILS_ENV: production
    ports:
      - "80:3000"  # Maps port 80 on the host to port 3000 in the container
    volumes:
      - .:/app
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
